name: 'Release to TER'

on:
  push:
    tags:
      - "**"

jobs:
  ci:
    uses: './.github/workflows/ci.yaml'

  ter-upload:
    name: 'Release 🚀'
    runs-on: 'ubuntu-22.04'
    needs:
      - 'ci'
    steps:
      - uses: 'actions/checkout@v1'
      - uses: 'tomasnorre/typo3-upload-ter@v2'
        name: 'Publish 🚀'
        with:
          api-token: ${{ secrets.TER_ACCESS_KEY }}
